# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-4-1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-4-1
pod "PGFramework"
  target 'Test-4-1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-4-1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
